FROM python:3.12-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/simplisafe-apple-home
COPY pyproject.toml README.md ./
COPY src ./src
RUN python3 -m pip install --no-cache-dir . livekit==1.1.10

ENTRYPOINT ["ssah-livekit"]
